name: Docs
on:
  push:
    branches:
      - main
      - npe2
  pull_request:
    branches:
      - main
      - npe2
  workflow_dispatch:
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: sudo apt-get install -y libxkbcommon-x11-0

      - name: Set QT_QPA_PLATFORM
        run: echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "napari[all]"
          pip install Sphinx sphinx-rtd-theme sphinx-tabs myst-parser

      - name: Sphinx build
        run: |
          pip install .
          cd ./docs
          sphinx-apidoc -T -f -e -o . ../src
          make html
          cd ..


  deploy:
    needs: docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4